version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - run:
          name: Checkout Dependencies
          command: git clone https://github.com/sdkitono/react-redux-ifgfseattle && git clone https://github.com/sdkitono/ifgf-backend
      - run:
          name: Print the Current Time
          command: date
