version: 2
jobs:
  build:
    docker:
      - image: keyclipse/docker_deploy
    steps:
      - checkout
      - run:
          name: Checkout Dependencies
          command: git clone https://github.com/sdkitono/react-redux-ifgfseattle && git clone https://github.com/sdkitono/ifgf-backend
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Docker Login
          command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Template
          command: FRONTEND_TAG=${CIRCLE_SHA1} BACKEND_TAG=${CIRCLE_SHA1} envsubst < ./docker-compose.template.yml > ./docker-compose.yml
      - run:
          name: Build Docker Compose
          command: docker-compose build
      - run:
          name: Push Docker Compose
          command: docker-compose push
